# action.yaml
name: 'Groq Code review Github Action'
author: vijayabhaskar78
description: 'A Github Action that posts code review from Groq to pull request'
inputs:
  github-token:
    description: 'The token used to authenticate with the GitHub API'
    required: false
    default: ${{ github.token }} #${{ secrets.GITHUB_TOKEN }}
  model:
    description: 'The Groq language model to use for code review'
    required: false
    default: 'llama-3.1-70b-versatile'
  groq-key:
    description: 'The Groq API key'
    required: true
  prompt:
    description: 'The prompt to use for the analysis.'
    required: false
    default: |
      Please review the code change below and provide feedback.
  post-if-error:
    description: 'Whether to post a comment if there was an error'
    required: false
    default: 'true'
  max-length:
    description: 'Maximum number of characters to submit to OpenAI'
    required: false
    default: 8000
  review-title:
    description: 'The title of the review'
    required: false
    default: '# Code Review by Groq'
  inline-comments:
    description: 'Enable inline comments on specific lines (true/false)'
    required: false
    default: 'true'

outputs:
  results:
    description: 'The results of the code review'
    value: ${{ steps.groq.outputs.reviewresult }}

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run Groq code review
      id: groq
      run: |
        # Save diff for line mapping
        git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.txt
        
        # Run analysis and get JSON output
        cat diff.txt | python ${{ github.action_path }}/analyze_code_changes.py > reviews.json
        
        # Check if inline comments are enabled
        if [ "$INLINE_COMMENTS" = "true" ]; then
          # Post inline review comments
          cat reviews.json | python ${{ github.action_path }}/post_review_comments.py
          echo "reviewresult=Posted inline review comments" >> $GITHUB_OUTPUT
        else
          # Fallback to old-style comment
          echo "$REVIEW_TITLE" > review.txt
          python ${{ github.action_path }}/format_review.py < reviews.json >> review.txt
          echo 'reviewresult<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat review.txt)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        fi
      shell: bash
      env:
        GROQ_API_KEY: ${{ inputs.groq-key }}
        MODEL: ${{ inputs.model }}
        PROMPT: ${{ inputs.prompt }}
        MAX_LENGTH: ${{ inputs.max-length }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT_TITLE: ${{ github.event.pull_request.title }}
        COMMIT_BODY: ${{ github.event.pull_request.body }}
        REVIEW_TITLE: ${{ inputs.review-title }}
        INLINE_COMMENTS: ${{ inputs.inline-comments }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        DIFF_FILE: diff.txt

    - name: Show output in case of failure
      id: err-output
      if: failure()
      run: |
        echo 'errorresult<<EOF' >> $GITHUB_OUTPUT
        echo "ERROR: $(cat review.txt)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        echo "Review result and error: $(cat review.txt)"
      shell: bash

    - name: Create comment
      if: (success() || (inputs.post-if-error && inputs.post-if-error != 'false')) && inputs.inline-comments != 'true'
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ steps.groq.outputs.reviewresult && steps.groq.outputs.reviewresult || steps.err-output.outputs.errorresult }}
        reactions: '+1'

branding:
  icon: 'user-check'
  color: 'green'
